### ISSUE TITLE
not return a View from onCreateView() or this was called before onCreateView().

### ISSUE THREAD

**Issue by IvanDeLucasRog** [yogacp/android-viewbinding#5]
I got these error

java.lang.IllegalStateException: Fragment ChooseLiftDialogFragment{fb1047b} (00f4882f-62df-43e0-8e64-d4926820a8b3 tag=ChooseLiftDialogFragment) did not return a View from onCreateView() or this was called before onCreateView().
        at androidx.fragment.app.Fragment.requireView(Fragment.java:1964)
        at android.viewbinding.library.fragment.FragmentViewBindingDelegate.getValue(FragmentBinding.kt:77)
        at com.ivandlrapp.virtualenconder.ui.main.ChooseLiftDialogFragment.getBinding(ChooseLiftDialogFragment.kt:17)
        at com.ivandlrapp.virtualenconder.ui.main.ChooseLiftDialogFragment.onCreateView(ChooseLiftDialogFragment.kt:24)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

I dont know where I call binding before onCreateView and I return binding.root there

`class ChooseLiftDialogFragment : DialogFragment() {

    private val binding: FragmentChooseLiftDialogBinding by viewBinding()

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        return binding.root
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setStyle(STYLE_NORMAL, R.style.DialogStyle)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        val squat = view.context.resources.getString(R.string.squat)
        val deadlidt = view.context.resources.getString(R.string.deadlift)

        binding.squatItem.setOnClickListener {
            ChooseModeDialogFragment().show(parentFragmentManager, "ChoseModeDialogFragment")
            PreferenceUtils.saveString(view.context, R.string.exercise_pref_key, squat)
            this.dismiss()
        }

        binding.deadliftItem.setOnClickListener {
            ChooseModeDialogFragment().show(parentFragmentManager, "ChoseModeDialogFragment")
            PreferenceUtils.saveString(view.context, R.string.exercise_pref_key, deadlidt)
            this.dismiss()
        }
    }
}`

Thanks

**Comment by yogacp** [comment]
Hi @IvanDeLucasRog ,
It seems you put the wrong import package. You want to use `viewBinding` for the DialogFragment(). But, you use the `viewBinding()` from the fragment. Just change the import package to this:
`import android.viewbinding.library.dialogfragment.viewBinding`

It should fix your issue.

**Comment by IvanDeLucasRog** [comment]
It was! Thanks, big support!

**Comment by yogacp** [comment]
Sure, you're welcome!
